
spring:
  jpa:
    database: POSTGRESQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5438/travel-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver